// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Gebruiker", b =>
                {
                    b.Property<int>("GebruikersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GebruikersID"));

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gebruikersnaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UiSettings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wachtwoord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GebruikersID");

                    b.ToTable("Gebruikers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("backend.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    //Where can I find IDENTITY_INSERT? You can find IDENTITY_INSERT in SQL Server, which is a setting that allows explicit values to be inserted into the identity column of a table. By default, SQL Server automatically generates values for identity columns, but when IDENTITY_INSERT is set to ON for a specific table, you can manually insert values into the identity column.
                    //Where is that setting? The IDENTITY_INSERT setting is controlled at the table level in SQL Server. You can enable or disable it using the following SQL commands:
                    /* To enable IDENTITY_INSERT for a table:
                     * SET IDENTITY_INSERT [TableName] ON;
                     */
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

b.Property<string>("Beschrijving")
    .IsRequired()
    .HasColumnType("nvarchar(max)");

b.Property<float?>("Eindprijs")
    .HasColumnType("real");

b.Property<float?>("MinPrijs")
    .HasColumnType("real");

b.Property<string>("Naam")
    .IsRequired()
    .HasColumnType("nvarchar(max)");

b.Property<float?>("StartPrijs")
    .HasColumnType("real");

b.Property<int?>("VeilerGebruikersID")
    .HasColumnType("int");

b.Property<int>("VerkoperID")
    .HasColumnType("int");

b.HasKey("ProductID");

b.HasIndex("VeilerGebruikersID");

b.ToTable("Producten");
});

modelBuilder.Entity("backend.Models.Veiling", b =>
{
b.Property<int>("VeilingID")
    .ValueGeneratedOnAdd()
    .HasColumnType("int");

SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VeilingID"));

b.Property<TimeSpan?>("EindTijd")
    .HasColumnType("time");

b.Property<int?>("KoperID")
    .HasColumnType("int");

b.Property<int>("ProductID")
    .HasColumnType("int");

b.Property<DateTime>("StartDatumTijd")
    .HasColumnType("datetime2");

b.Property<float?>("VerkoopPrijs")
    .HasColumnType("real");

b.Property<int>("VerkoperID")
    .HasColumnType("int");

b.HasKey("VeilingID");

b.HasIndex("KoperID");

b.ToTable("Veilingen");
});

modelBuilder.Entity("backend.Models.Admin", b =>
{
b.HasBaseType("backend.Models.Gebruiker");

b.ToTable("Admins", (string)null);
});

modelBuilder.Entity("backend.Models.Koper", b =>
{
b.HasBaseType("backend.Models.Gebruiker");

b.ToTable("Kopers", (string)null);
});

modelBuilder.Entity("backend.Models.Veiler", b =>
{
b.HasBaseType("backend.Models.Gebruiker");

b.Property<string>("KvkNummer")
    .IsRequired()
    .HasColumnType("nvarchar(max)");

b.ToTable("Veilers", (string)null);
});

modelBuilder.Entity("backend.Models.Product", b =>
{
b.HasOne("backend.Models.Veiler", null)
    .WithMany("Producten")
    .HasForeignKey("VeilerGebruikersID");
});

modelBuilder.Entity("backend.Models.Veiling", b =>
{
b.HasOne("backend.Models.Koper", null)
    .WithMany("GewonnenVeilingen")
    .HasForeignKey("KoperID");
});

modelBuilder.Entity("backend.Models.Admin", b =>
{
b.HasOne("backend.Models.Gebruiker", null)
    .WithOne()
    .HasForeignKey("backend.Models.Admin", "GebruikersID")
    .OnDelete(DeleteBehavior.Cascade)
    .IsRequired();
});

modelBuilder.Entity("backend.Models.Koper", b =>
{
b.HasOne("backend.Models.Gebruiker", null)
    .WithOne()
    .HasForeignKey("backend.Models.Koper", "GebruikersID")
    .OnDelete(DeleteBehavior.Cascade)
    .IsRequired();
});

modelBuilder.Entity("backend.Models.Veiler", b =>
{
b.HasOne("backend.Models.Gebruiker", null)
    .WithOne()
    .HasForeignKey("backend.Models.Veiler", "GebruikersID")
    .OnDelete(DeleteBehavior.Cascade)
    .IsRequired();
});

modelBuilder.Entity("backend.Models.Koper", b =>
{
b.Navigation("GewonnenVeilingen");
});

modelBuilder.Entity("backend.Models.Veiler", b =>
{
b.Navigation("Producten");
});
#pragma warning restore 612, 618
}
}
}
